/**
 * Task 23: Seed Demo Profiles
 *
 * Seeds 50 diverse demo profiles into the Supabase `users` table.
 *
 * Usage:
 *   npx tsx scripts/seed-profiles.ts          # insert 50 demo profiles
 *   npx tsx scripts/seed-profiles.ts --clean   # delete existing demos first, then insert
 */

import 'dotenv/config'
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseServiceKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey)

interface DemoProfile {
  id: string
  email: string
  name: string
  age: number
  bio: string
  gender: 'male' | 'female' | 'nonbinary'
  looking_for: 'male' | 'female' | 'everyone'
  location: string
  horoscope: string
  personality: {
    friday_night: string
    argue_style: string
    love_language: string
    social_energy: string
    adventure_level: string
    communication: string
    humor_style: string
    relationship_pace: string
  }
  soul_type: 'romantic' | 'funny' | 'bold' | 'intellectual'
  role: 'chaser' | 'gatekeeper'
  agent_appearance: {
    body: number
    skinTone: number
    hair: number
    hairColor: number
    top: number
    bottom: number
    accessories: string[]
  }
  photos: string[]
  tier: 'free'
  is_demo: boolean
}

// Generate a deterministic UUID-like ID from a seed number
function demoId(n: number): string {
  const hex = n.toString(16).padStart(4, '0')
  return `00000000-demo-4000-a000-${hex.padStart(12, '0')}`
}

const PROFILES: DemoProfile[] = [
  // ── 1-10 ──────────────────────────────────────────────────
  {
    id: demoId(1),
    email: 'demo-luna@pixemingle.dev',
    name: 'Luna Rivera',
    age: 24,
    bio: 'Pixel witch brewing potions and playlists.',
    gender: 'female',
    looking_for: 'male',
    location: 'Los Angeles, CA',
    horoscope: 'Aries',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Passionate debate',
      love_language: 'Physical touch',
      social_energy: 'Start dancing',
      adventure_level: 'Already packing',
      communication: 'Voice notes',
      humor_style: 'Dark humor',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'bold',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 3, hair: 2, hairColor: 4, top: 0, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/luna/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(2),
    email: 'demo-kai@pixemingle.dev',
    name: 'Kai Nakamura',
    age: 28,
    bio: 'Code by day, ramen connoisseur by night.',
    gender: 'male',
    looking_for: 'female',
    location: 'San Francisco, CA',
    horoscope: 'Taurus',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Talk it out',
      love_language: 'Quality time',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'intellectual',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 2, hair: 1, hairColor: 0, top: 1, bottom: 0, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/kai/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(3),
    email: 'demo-aaliyah@pixemingle.dev',
    name: 'Aaliyah Washington',
    age: 26,
    bio: 'Dancing through life one pixel at a time.',
    gender: 'female',
    looking_for: 'everyone',
    location: 'Atlanta, GA',
    horoscope: 'Gemini',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Humor defuses',
      love_language: 'Words of affirmation',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'Memes only',
      humor_style: 'Slapstick',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'funny',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 4, hair: 4, hairColor: 1, top: 2, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/aaliyah/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(4),
    email: 'demo-mateo@pixemingle.dev',
    name: 'Mateo Garcia',
    age: 31,
    bio: 'Guitar player who believes every date deserves a soundtrack.',
    gender: 'male',
    looking_for: 'female',
    location: 'Miami, FL',
    horoscope: 'Cancer',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Acts of service',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Only if someone else plans',
      communication: 'Voice notes',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 3, hair: 0, hairColor: 2, top: 3, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/mateo/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(5),
    email: 'demo-sage@pixemingle.dev',
    name: 'Sage Kim',
    age: 23,
    bio: 'Nonbinary artist painting the internet one sprite at a time.',
    gender: 'nonbinary',
    looking_for: 'everyone',
    location: 'Portland, OR',
    horoscope: 'Leo',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Avoid conflict',
      love_language: 'Gifts',
      social_energy: 'Leave early',
      adventure_level: 'Already packing',
      communication: 'Memes only',
      humor_style: 'Dark humor',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'intellectual',
    role: 'gatekeeper',
    agent_appearance: { body: 2, skinTone: 1, hair: 3, hairColor: 3, top: 4, bottom: 2, accessories: ['acc_hat'] },
    photos: ['https://picsum.photos/seed/sage/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(6),
    email: 'demo-priya@pixemingle.dev',
    name: 'Priya Sharma',
    age: 27,
    bio: 'Bollywood heart in a pixel world.',
    gender: 'female',
    looking_for: 'male',
    location: 'New York, NY',
    horoscope: 'Virgo',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Passionate debate',
      love_language: 'Words of affirmation',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'romantic',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 3, hair: 4, hairColor: 0, top: 2, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/priya/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(7),
    email: 'demo-jackson@pixemingle.dev',
    name: 'Jackson O\'Brien',
    age: 34,
    bio: 'Irish charm, terrible at cooking, great at compliments.',
    gender: 'male',
    looking_for: 'female',
    location: 'Boston, MA',
    horoscope: 'Libra',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Humor defuses',
      love_language: 'Physical touch',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'One-liners',
      humor_style: 'Slapstick',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'funny',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 0, hair: 0, hairColor: 4, top: 1, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/jackson/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(8),
    email: 'demo-amara@pixemingle.dev',
    name: 'Amara Okafor',
    age: 29,
    bio: 'Undefeated at board games. Try me.',
    gender: 'female',
    looking_for: 'everyone',
    location: 'Chicago, IL',
    horoscope: 'Scorpio',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Passionate debate',
      love_language: 'Quality time',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'Paragraphs',
      humor_style: 'Dark humor',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'bold',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 4, hair: 3, hairColor: 0, top: 0, bottom: 2, accessories: ['acc_crown'] },
    photos: ['https://picsum.photos/seed/amara/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(9),
    email: 'demo-liam@pixemingle.dev',
    name: 'Liam Chen',
    age: 25,
    bio: 'Boba tea enthusiast and retro game collector.',
    gender: 'male',
    looking_for: 'male',
    location: 'Seattle, WA',
    horoscope: 'Sagittarius',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Avoid conflict',
      love_language: 'Gifts',
      social_energy: 'Leave early',
      adventure_level: 'Hard pass',
      communication: 'Memes only',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 2, hair: 2, hairColor: 0, top: 3, bottom: 0, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/liamchen/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(10),
    email: 'demo-freya@pixemingle.dev',
    name: 'Freya Lindqvist',
    age: 22,
    bio: 'Scandinavian minimalist with a maximalist heart.',
    gender: 'female',
    looking_for: 'male',
    location: 'Denver, CO',
    horoscope: 'Capricorn',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Acts of service',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'intellectual',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 0, hair: 4, hairColor: 3, top: 3, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/freya/400/400'],
    tier: 'free',
    is_demo: true,
  },

  // ── 11-20 ──────────────────────────────────────────────────
  {
    id: demoId(11),
    email: 'demo-devon@pixemingle.dev',
    name: 'Devon Parker',
    age: 30,
    bio: 'Nonbinary barista who can read your aura through latte art.',
    gender: 'nonbinary',
    looking_for: 'everyone',
    location: 'Austin, TX',
    horoscope: 'Aquarius',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Humor defuses',
      love_language: 'Words of affirmation',
      social_energy: 'Start dancing',
      adventure_level: 'Already packing',
      communication: 'Voice notes',
      humor_style: 'Slapstick',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'funny',
    role: 'chaser',
    agent_appearance: { body: 2, skinTone: 2, hair: 1, hairColor: 4, top: 4, bottom: 3, accessories: [] },
    photos: ['https://picsum.photos/seed/devon/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(12),
    email: 'demo-sofia@pixemingle.dev',
    name: 'Sofia Morales',
    age: 26,
    bio: 'Salsa dancer who will judge you by your rhythm.',
    gender: 'female',
    looking_for: 'male',
    location: 'Phoenix, AZ',
    horoscope: 'Pisces',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Passionate debate',
      love_language: 'Physical touch',
      social_energy: 'Start dancing',
      adventure_level: 'Already packing',
      communication: 'One-liners',
      humor_style: 'Slapstick',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'bold',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 3, hair: 4, hairColor: 2, top: 0, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/sofia/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(13),
    email: 'demo-hassan@pixemingle.dev',
    name: 'Hassan Ali',
    age: 33,
    bio: 'Poet trapped in an engineer\'s body.',
    gender: 'male',
    looking_for: 'female',
    location: 'Houston, TX',
    horoscope: 'Aries',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Words of affirmation',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Only if someone else plans',
      communication: 'Paragraphs',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 3, hair: 0, hairColor: 0, top: 3, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/hassan/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(14),
    email: 'demo-mei@pixemingle.dev',
    name: 'Mei Zhang',
    age: 24,
    bio: 'Cat mom, dim sum queen, and pixel perfectionist.',
    gender: 'female',
    looking_for: 'everyone',
    location: 'San Jose, CA',
    horoscope: 'Taurus',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Avoid conflict',
      love_language: 'Gifts',
      social_energy: 'Leave early',
      adventure_level: 'Hard pass',
      communication: 'Memes only',
      humor_style: 'Dark humor',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'intellectual',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 1, hair: 3, hairColor: 0, top: 2, bottom: 1, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/mei/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(15),
    email: 'demo-tyler@pixemingle.dev',
    name: 'Tyler Brooks',
    age: 27,
    bio: 'Gym bro with a secret poetry journal.',
    gender: 'male',
    looking_for: 'female',
    location: 'Nashville, TN',
    horoscope: 'Gemini',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Passionate debate',
      love_language: 'Physical touch',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'One-liners',
      humor_style: 'Slapstick',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'bold',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 0, hair: 0, hairColor: 1, top: 4, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/tyler/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(16),
    email: 'demo-yuki@pixemingle.dev',
    name: 'Yuki Tanaka',
    age: 29,
    bio: 'Anime nerd who cooks better than your grandma.',
    gender: 'female',
    looking_for: 'male',
    location: 'San Diego, CA',
    horoscope: 'Cancer',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Talk it out',
      love_language: 'Acts of service',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'romantic',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 1, hair: 4, hairColor: 0, top: 2, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/yuki/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(17),
    email: 'demo-noah@pixemingle.dev',
    name: 'Noah Williams',
    age: 35,
    bio: 'Dad jokes are a love language. Fight me.',
    gender: 'male',
    looking_for: 'everyone',
    location: 'Philadelphia, PA',
    horoscope: 'Leo',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Humor defuses',
      love_language: 'Quality time',
      social_energy: 'Work the room',
      adventure_level: 'Only if someone else plans',
      communication: 'One-liners',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'funny',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 4, hair: 0, hairColor: 0, top: 1, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/noah/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(18),
    email: 'demo-ava@pixemingle.dev',
    name: 'Ava Kowalski',
    age: 22,
    bio: 'Bookworm who believes in love at first chapter.',
    gender: 'female',
    looking_for: 'female',
    location: 'Minneapolis, MN',
    horoscope: 'Virgo',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Avoid conflict',
      love_language: 'Words of affirmation',
      social_energy: 'Leave early',
      adventure_level: 'Hard pass',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 0, hair: 2, hairColor: 4, top: 3, bottom: 1, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/ava/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(19),
    email: 'demo-omar@pixemingle.dev',
    name: 'Omar Farah',
    age: 28,
    bio: 'Basketball, baklava, and bad puns.',
    gender: 'male',
    looking_for: 'female',
    location: 'Columbus, OH',
    horoscope: 'Libra',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Humor defuses',
      love_language: 'Physical touch',
      social_energy: 'Start dancing',
      adventure_level: 'Already packing',
      communication: 'Voice notes',
      humor_style: 'Slapstick',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'funny',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 3, hair: 1, hairColor: 0, top: 0, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/omar/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(20),
    email: 'demo-zara@pixemingle.dev',
    name: 'Zara Patel',
    age: 25,
    bio: 'Startup founder by day, pixel dater by night.',
    gender: 'female',
    looking_for: 'male',
    location: 'Raleigh, NC',
    horoscope: 'Scorpio',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Passionate debate',
      love_language: 'Quality time',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'bold',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 3, hair: 4, hairColor: 0, top: 2, bottom: 2, accessories: [] },
    photos: ['https://picsum.photos/seed/zara/400/400'],
    tier: 'free',
    is_demo: true,
  },

  // ── 21-30 ──────────────────────────────────────────────────
  {
    id: demoId(21),
    email: 'demo-felix@pixemingle.dev',
    name: 'Felix Dubois',
    age: 32,
    bio: 'French accent, questionable fashion, excellent kisser (allegedly).',
    gender: 'male',
    looking_for: 'female',
    location: 'New Orleans, LA',
    horoscope: 'Sagittarius',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Passionate debate',
      love_language: 'Physical touch',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'Voice notes',
      humor_style: 'Dark humor',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'bold',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 1, hair: 2, hairColor: 2, top: 1, bottom: 3, accessories: [] },
    photos: ['https://picsum.photos/seed/felix/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(22),
    email: 'demo-iris@pixemingle.dev',
    name: 'Iris Thompson',
    age: 21,
    bio: 'Plant mom of 47. Yes, they all have names.',
    gender: 'female',
    looking_for: 'everyone',
    location: 'Portland, OR',
    horoscope: 'Capricorn',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Avoid conflict',
      love_language: 'Acts of service',
      social_energy: 'Leave early',
      adventure_level: 'Need a week to plan',
      communication: 'Memes only',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 0, hair: 3, hairColor: 1, top: 4, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/iris/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(23),
    email: 'demo-river@pixemingle.dev',
    name: 'River Blackwood',
    age: 26,
    bio: 'Nonbinary musician. My love language is sharing headphones.',
    gender: 'nonbinary',
    looking_for: 'everyone',
    location: 'Nashville, TN',
    horoscope: 'Aquarius',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Quality time',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Only if someone else plans',
      communication: 'Voice notes',
      humor_style: 'Dry wit',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'intellectual',
    role: 'chaser',
    agent_appearance: { body: 2, skinTone: 1, hair: 1, hairColor: 3, top: 0, bottom: 2, accessories: ['acc_hat'] },
    photos: ['https://picsum.photos/seed/river/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(24),
    email: 'demo-elena@pixemingle.dev',
    name: 'Elena Petrova',
    age: 30,
    bio: 'Chess grandmaster energy, checkers patience.',
    gender: 'female',
    looking_for: 'male',
    location: 'Chicago, IL',
    horoscope: 'Pisces',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Passionate debate',
      love_language: 'Words of affirmation',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'intellectual',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 0, hair: 4, hairColor: 3, top: 2, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/elena/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(25),
    email: 'demo-dante@pixemingle.dev',
    name: 'Dante Robinson',
    age: 36,
    bio: 'Chef who thinks food is the real love language.',
    gender: 'male',
    looking_for: 'female',
    location: 'Detroit, MI',
    horoscope: 'Aries',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Talk it out',
      love_language: 'Acts of service',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'One-liners',
      humor_style: 'Slapstick',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'funny',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 4, hair: 0, hairColor: 0, top: 1, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/dante/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(26),
    email: 'demo-nina@pixemingle.dev',
    name: 'Nina Johansson',
    age: 28,
    bio: 'Swedish gamer girl. Will destroy you at Mario Kart.',
    gender: 'female',
    looking_for: 'male',
    location: 'Seattle, WA',
    horoscope: 'Taurus',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Humor defuses',
      love_language: 'Quality time',
      social_energy: 'Leave early',
      adventure_level: 'Hard pass',
      communication: 'Memes only',
      humor_style: 'Dark humor',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'funny',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 0, hair: 2, hairColor: 4, top: 0, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/nina/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(27),
    email: 'demo-marcus@pixemingle.dev',
    name: 'Marcus Lee',
    age: 40,
    bio: 'Silver fox who still plays DDR unironically.',
    gender: 'male',
    looking_for: 'everyone',
    location: 'San Francisco, CA',
    horoscope: 'Gemini',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Talk it out',
      love_language: 'Quality time',
      social_energy: 'Start dancing',
      adventure_level: 'Only if someone else plans',
      communication: 'Paragraphs',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 2, hair: 0, hairColor: 1, top: 3, bottom: 3, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/marcus/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(28),
    email: 'demo-destiny@pixemingle.dev',
    name: 'Destiny Howard',
    age: 23,
    bio: 'Astrology truther and tarot reader. Mercury is always in retrograde.',
    gender: 'female',
    looking_for: 'female',
    location: 'Austin, TX',
    horoscope: 'Cancer',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Avoid conflict',
      love_language: 'Gifts',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Voice notes',
      humor_style: 'Dark humor',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'romantic',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 4, hair: 3, hairColor: 2, top: 4, bottom: 1, accessories: ['acc_crown'] },
    photos: ['https://picsum.photos/seed/destiny/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(29),
    email: 'demo-ravi@pixemingle.dev',
    name: 'Ravi Gupta',
    age: 31,
    bio: 'Debate champion turned conflict-avoidant boyfriend material.',
    gender: 'male',
    looking_for: 'female',
    location: 'Dallas, TX',
    horoscope: 'Leo',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Avoid conflict',
      love_language: 'Acts of service',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'intellectual',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 3, hair: 1, hairColor: 0, top: 3, bottom: 0, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/ravi/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(30),
    email: 'demo-mila@pixemingle.dev',
    name: 'Mila Santos',
    age: 27,
    bio: 'Muay Thai by morning, pixel dates by moonlight.',
    gender: 'female',
    looking_for: 'male',
    location: 'Las Vegas, NV',
    horoscope: 'Virgo',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Passionate debate',
      love_language: 'Physical touch',
      social_energy: 'Start dancing',
      adventure_level: 'Already packing',
      communication: 'One-liners',
      humor_style: 'Slapstick',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'bold',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 3, hair: 4, hairColor: 0, top: 4, bottom: 2, accessories: [] },
    photos: ['https://picsum.photos/seed/mila/400/400'],
    tier: 'free',
    is_demo: true,
  },

  // ── 31-40 ──────────────────────────────────────────────────
  {
    id: demoId(31),
    email: 'demo-ash@pixemingle.dev',
    name: 'Ash Reyes',
    age: 25,
    bio: 'Nonbinary skateboarder who believes in love at first kickflip.',
    gender: 'nonbinary',
    looking_for: 'everyone',
    location: 'Los Angeles, CA',
    horoscope: 'Libra',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Humor defuses',
      love_language: 'Quality time',
      social_energy: 'Start dancing',
      adventure_level: 'Already packing',
      communication: 'Memes only',
      humor_style: 'Slapstick',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'funny',
    role: 'chaser',
    agent_appearance: { body: 2, skinTone: 3, hair: 0, hairColor: 4, top: 0, bottom: 2, accessories: ['acc_hat'] },
    photos: ['https://picsum.photos/seed/ash/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(32),
    email: 'demo-chloe@pixemingle.dev',
    name: 'Chloe Nguyen',
    age: 24,
    bio: 'Coffee snob and pixel art purist. No anti-aliasing allowed.',
    gender: 'female',
    looking_for: 'male',
    location: 'Portland, OR',
    horoscope: 'Scorpio',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Gifts',
      social_energy: 'Leave early',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'intellectual',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 2, hair: 3, hairColor: 0, top: 2, bottom: 1, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/chloe/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(33),
    email: 'demo-jamal@pixemingle.dev',
    name: 'Jamal Carter',
    age: 29,
    bio: 'Photographer who sees the world in 16x16 grids.',
    gender: 'male',
    looking_for: 'female',
    location: 'Atlanta, GA',
    horoscope: 'Sagittarius',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Words of affirmation',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Already packing',
      communication: 'Voice notes',
      humor_style: 'Dark humor',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'romantic',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 4, hair: 1, hairColor: 0, top: 1, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/jamal/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(34),
    email: 'demo-hana@pixemingle.dev',
    name: 'Hana Park',
    age: 26,
    bio: 'K-drama addict seeking my own main character moment.',
    gender: 'female',
    looking_for: 'male',
    location: 'New York, NY',
    horoscope: 'Capricorn',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Passionate debate',
      love_language: 'Words of affirmation',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Only if someone else plans',
      communication: 'Paragraphs',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'romantic',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 1, hair: 4, hairColor: 0, top: 3, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/hana/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(35),
    email: 'demo-alex@pixemingle.dev',
    name: 'Alex Moreno',
    age: 33,
    bio: 'Nonbinary rock climber. Will belay you on the first date.',
    gender: 'nonbinary',
    looking_for: 'everyone',
    location: 'Boulder, CO',
    horoscope: 'Aquarius',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Talk it out',
      love_language: 'Physical touch',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'One-liners',
      humor_style: 'Dry wit',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'bold',
    role: 'chaser',
    agent_appearance: { body: 2, skinTone: 3, hair: 0, hairColor: 2, top: 4, bottom: 2, accessories: [] },
    photos: ['https://picsum.photos/seed/alexm/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(36),
    email: 'demo-nadia@pixemingle.dev',
    name: 'Nadia Volkov',
    age: 28,
    bio: 'Ballet dancer with a punk rock soul.',
    gender: 'female',
    looking_for: 'male',
    location: 'Miami, FL',
    horoscope: 'Pisces',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Passionate debate',
      love_language: 'Physical touch',
      social_energy: 'Start dancing',
      adventure_level: 'Only if someone else plans',
      communication: 'Voice notes',
      humor_style: 'Dark humor',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'bold',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 0, hair: 2, hairColor: 4, top: 0, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/nadia/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(37),
    email: 'demo-elijah@pixemingle.dev',
    name: 'Elijah Brown',
    age: 38,
    bio: 'Vinyl collector. My love language is a perfectly curated playlist.',
    gender: 'male',
    looking_for: 'female',
    location: 'Memphis, TN',
    horoscope: 'Aries',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Talk it out',
      love_language: 'Quality time',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Hard pass',
      communication: 'Paragraphs',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 4, hair: 0, hairColor: 0, top: 1, bottom: 3, accessories: [] },
    photos: ['https://picsum.photos/seed/elijah/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(38),
    email: 'demo-camille@pixemingle.dev',
    name: 'Camille Laurent',
    age: 25,
    bio: 'French pastry student. Will win you over with croissants.',
    gender: 'female',
    looking_for: 'everyone',
    location: 'Washington, DC',
    horoscope: 'Taurus',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Avoid conflict',
      love_language: 'Acts of service',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Voice notes',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 1, hair: 4, hairColor: 3, top: 2, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/camille/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(39),
    email: 'demo-jaden@pixemingle.dev',
    name: 'Jaden Mitchell',
    age: 23,
    bio: 'Twitch streamer looking for a player two.',
    gender: 'male',
    looking_for: 'male',
    location: 'Orlando, FL',
    horoscope: 'Gemini',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Humor defuses',
      love_language: 'Quality time',
      social_energy: 'Leave early',
      adventure_level: 'Hard pass',
      communication: 'Memes only',
      humor_style: 'Slapstick',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'funny',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 4, hair: 2, hairColor: 1, top: 0, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/jaden/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(40),
    email: 'demo-rosa@pixemingle.dev',
    name: 'Rosa Delgado',
    age: 34,
    bio: 'Lawyer by day, pixel matchmaker by night.',
    gender: 'female',
    looking_for: 'male',
    location: 'Houston, TX',
    horoscope: 'Cancer',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Passionate debate',
      love_language: 'Words of affirmation',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'Paragraphs',
      humor_style: 'Dark humor',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'bold',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 3, hair: 3, hairColor: 2, top: 2, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/rosa/400/400'],
    tier: 'free',
    is_demo: true,
  },

  // ── 41-50 ──────────────────────────────────────────────────
  {
    id: demoId(41),
    email: 'demo-sam@pixemingle.dev',
    name: 'Sam Adeyemi',
    age: 27,
    bio: 'Afrobeat DJ spinning love into every set.',
    gender: 'male',
    looking_for: 'female',
    location: 'Brooklyn, NY',
    horoscope: 'Leo',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Humor defuses',
      love_language: 'Physical touch',
      social_energy: 'Start dancing',
      adventure_level: 'Already packing',
      communication: 'Voice notes',
      humor_style: 'Slapstick',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'bold',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 4, hair: 1, hairColor: 0, top: 4, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/sam/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(42),
    email: 'demo-vivian@pixemingle.dev',
    name: 'Vivian Wu',
    age: 29,
    bio: 'Architect who designs love in perfect proportions.',
    gender: 'female',
    looking_for: 'female',
    location: 'San Francisco, CA',
    horoscope: 'Virgo',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Acts of service',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'intellectual',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 1, hair: 3, hairColor: 0, top: 3, bottom: 1, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/vivian/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(43),
    email: 'demo-kai-nb@pixemingle.dev',
    name: 'Kai Jordan',
    age: 22,
    bio: 'Nonbinary poet who rhymes hearts into alignment.',
    gender: 'nonbinary',
    looking_for: 'everyone',
    location: 'Asheville, NC',
    horoscope: 'Libra',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Avoid conflict',
      love_language: 'Words of affirmation',
      social_energy: 'Leave early',
      adventure_level: 'Only if someone else plans',
      communication: 'Paragraphs',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'chaser',
    agent_appearance: { body: 2, skinTone: 2, hair: 4, hairColor: 3, top: 0, bottom: 3, accessories: [] },
    photos: ['https://picsum.photos/seed/kaij/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(44),
    email: 'demo-tanya@pixemingle.dev',
    name: 'Tanya Ivanova',
    age: 31,
    bio: 'Competitive chess player. My opening move is always bold.',
    gender: 'female',
    looking_for: 'male',
    location: 'Boston, MA',
    horoscope: 'Scorpio',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Passionate debate',
      love_language: 'Quality time',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'One-liners',
      humor_style: 'Dark humor',
      relationship_pace: 'Define everything upfront',
    },
    soul_type: 'intellectual',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 0, hair: 4, hairColor: 4, top: 2, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/tanya/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(45),
    email: 'demo-diego@pixemingle.dev',
    name: 'Diego Fernandez',
    age: 37,
    bio: 'Taco truck philosopher with a heart of gold.',
    gender: 'male',
    looking_for: 'female',
    location: 'San Antonio, TX',
    horoscope: 'Sagittarius',
    personality: {
      friday_night: 'Adventurous outing',
      argue_style: 'Humor defuses',
      love_language: 'Acts of service',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'One-liners',
      humor_style: 'Slapstick',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'funny',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 3, hair: 0, hairColor: 0, top: 1, bottom: 0, accessories: ['acc_hat'] },
    photos: ['https://picsum.photos/seed/diego/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(46),
    email: 'demo-leah@pixemingle.dev',
    name: 'Leah Goldstein',
    age: 26,
    bio: 'Stand-up comic. My therapist says I use humor as a defense mechanism.',
    gender: 'female',
    looking_for: 'everyone',
    location: 'Chicago, IL',
    horoscope: 'Capricorn',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Humor defuses',
      love_language: 'Physical touch',
      social_energy: 'Work the room',
      adventure_level: 'Only if someone else plans',
      communication: 'One-liners',
      humor_style: 'Dark humor',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'funny',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 0, hair: 2, hairColor: 2, top: 0, bottom: 1, accessories: [] },
    photos: ['https://picsum.photos/seed/leah/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(47),
    email: 'demo-andre@pixemingle.dev',
    name: 'Andre Baptiste',
    age: 42,
    bio: 'Jazz pianist. Every conversation is an improvisation.',
    gender: 'male',
    looking_for: 'female',
    location: 'New Orleans, LA',
    horoscope: 'Aquarius',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Quality time',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Only if someone else plans',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'intellectual',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 4, hair: 0, hairColor: 0, top: 3, bottom: 3, accessories: ['acc_glasses'] },
    photos: ['https://picsum.photos/seed/andre/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(48),
    email: 'demo-maya@pixemingle.dev',
    name: 'Maya Osei',
    age: 24,
    bio: 'Fashion student who can judge your entire personality by your shoes.',
    gender: 'female',
    looking_for: 'male',
    location: 'New York, NY',
    horoscope: 'Pisces',
    personality: {
      friday_night: 'Social gathering',
      argue_style: 'Passionate debate',
      love_language: 'Gifts',
      social_energy: 'Work the room',
      adventure_level: 'Already packing',
      communication: 'Memes only',
      humor_style: 'Slapstick',
      relationship_pace: 'Jump right in',
    },
    soul_type: 'bold',
    role: 'gatekeeper',
    agent_appearance: { body: 1, skinTone: 4, hair: 3, hairColor: 1, top: 4, bottom: 2, accessories: ['acc_crown'] },
    photos: ['https://picsum.photos/seed/maya/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(49),
    email: 'demo-ben@pixemingle.dev',
    name: 'Ben Yamamoto',
    age: 30,
    bio: 'Sushi chef who believes presentation is everything.',
    gender: 'male',
    looking_for: 'male',
    location: 'Honolulu, HI',
    horoscope: 'Aries',
    personality: {
      friday_night: 'Cozy night in',
      argue_style: 'Talk it out',
      love_language: 'Acts of service',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Voice notes',
      humor_style: 'Puns and wordplay',
      relationship_pace: 'Slow burn',
    },
    soul_type: 'romantic',
    role: 'chaser',
    agent_appearance: { body: 0, skinTone: 2, hair: 1, hairColor: 0, top: 2, bottom: 0, accessories: [] },
    photos: ['https://picsum.photos/seed/ben/400/400'],
    tier: 'free',
    is_demo: true,
  },
  {
    id: demoId(50),
    email: 'demo-quinn@pixemingle.dev',
    name: 'Quinn Okonkwo',
    age: 28,
    bio: 'Nonbinary game designer crafting love stories in 8-bit.',
    gender: 'nonbinary',
    looking_for: 'everyone',
    location: 'Denver, CO',
    horoscope: 'Taurus',
    personality: {
      friday_night: 'Creative project',
      argue_style: 'Talk it out',
      love_language: 'Quality time',
      social_energy: 'Find one person to talk to deeply',
      adventure_level: 'Need a week to plan',
      communication: 'Paragraphs',
      humor_style: 'Dry wit',
      relationship_pace: 'Let it happen naturally',
    },
    soul_type: 'intellectual',
    role: 'gatekeeper',
    agent_appearance: { body: 2, skinTone: 4, hair: 2, hairColor: 3, top: 1, bottom: 2, accessories: ['acc_hat'] },
    photos: ['https://picsum.photos/seed/quinn/400/400'],
    tier: 'free',
    is_demo: true,
  },
]

async function main() {
  const cleanFirst = process.argv.includes('--clean')

  console.log(`Seeding ${PROFILES.length} demo profiles...`)

  if (cleanFirst) {
    console.log('Cleaning existing demo profiles...')
    const { error } = await supabase
      .from('users')
      .delete()
      .eq('is_demo', true)

    if (error) {
      console.error('Failed to clean demo profiles:', error.message)
      process.exit(1)
    }
    console.log('Existing demo profiles deleted.')
  }

  const BATCH_SIZE = 10
  let inserted = 0

  for (let i = 0; i < PROFILES.length; i += BATCH_SIZE) {
    const batch = PROFILES.slice(i, i + BATCH_SIZE)
    const batchNum = Math.floor(i / BATCH_SIZE) + 1
    const totalBatches = Math.ceil(PROFILES.length / BATCH_SIZE)

    console.log(`Inserting batch ${batchNum}/${totalBatches} (${batch.length} profiles)...`)

    const { error } = await supabase
      .from('users')
      .upsert(batch, { onConflict: 'id' })

    if (error) {
      console.error(`Batch ${batchNum} failed:`, error.message)
      process.exit(1)
    }

    inserted += batch.length
    console.log(`  Done. ${inserted}/${PROFILES.length} inserted.`)
  }

  console.log(`\nSuccessfully seeded ${inserted} demo profiles!`)
}

main().catch((err) => {
  console.error('Unexpected error:', err)
  process.exit(1)
})
